services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: shoply
      POSTGRES_PASSWORD: shoply
      POSTGRES_DB: shoply
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
